variables:
  DOCKER_DRIVER: overlay
  CONTAINER_APP_IMAGE: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_TAG
  CONTAINER_NGINX_IMAGE: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_TAG

stages:
  - build
  - deploy

.build_template: &build_definition
  stage: build
  image: docker:17.06.0
  services:
    - docker:17.06.0-dind

build app:
  <<: *build_definition
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --tag $CONTAINER_APP_IMAGE app/
    - docker push $CONTAINER_APP_IMAGE
  only:
    - tags

build nginx:
  <<: *build_definition
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --tag $CONTAINER_NGINX_IMAGE nginx/
    - docker push $CONTAINER_NGINX_IMAGE
  only:
    - tags

.deploy_template: &deploy_definition
  stage: deploy
  image: identt/rancher-compose:0.12.5
  script:
    - rancher-compose -f $DOCKER_COMPOSE_FILE --url $RANCHER_PROJECT_URL --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY -p $RANCHER_PROJECT_NAME up -d --confirm-upgrade
    - rancher-compose -f $DOCKER_COMPOSE_FILE --url $RANCHER_PROJECT_URL --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY -p $RANCHER_PROJECT_NAME up -d --force-upgrade --pull $RANCHER_COMPONENTS

deploy techbranch:
  <<: *deploy_definition
  environment:
    name: production
    url: https://monitor.techbranch.net
  variables:
    RANCHER_PROJECT_URL: https://rancher.techbranch.net/v1/projects/1a116
    RANCHER_ACCESS_KEY: 1615CCDDB775869057BF
    RANCHER_SECRET_KEY: GjEwzmxPxmusxYkJA7GjioihXAWHk835L8w3Vx5K
    RANCHER_PROJECT_NAME: util-frontend
    RANCHER_COMPONENTS: app
    DOCKER_COMPOSE_FILE: docker-compose.prod.yml
  only:
    - tags
